remove unloadable
resolves error "NameError: undefined local variable or method `unloadable' for Plutus::EntriesController:Class"
unloadable method does not exist any more in activesupport